service: graphql-serverless # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  profile: ${opt:profile, 'crowdsys-umar'}
  region: ap-southeast-1
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 60 # optional, in seconds, default is 6
  versionFunctions: ${opt:alias, 'dev'}
  role: arn:aws:iam::747465455461:role/DevTeamLambdaExecutionRole
  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: "*"

functions:
  graphql:
    handler: handler.graphqlHandler
    vpc:
      securityGroupIds:
        - sg-022590fed1472d062
      subnetIds:
        - subnet-0803b4b1cfc1fcb33
        - subnet-07321b6bf83806078
    events:
      - http: 'GET /graphql'
      - http: 'POST /dev/graphql'


plugins:
  - serverless-offline
  - serverless-webpack

custom:
  serverless-offline:
    dontPrintOutput: true
    port: 4000
  webpackIncludeModules: true